### ISSUE TITLE
Correction d'une faute d'orthographe

### ISSUE THREAD

**Issue by JulesSerra** [ub-mmi-but/git-101#104]
Dans la partie II), création d'un repository,

>Maintenant qu'Emma à créé le projet sur Github, elle doit maintenant créer le dossier qui acceuillera le projet sur sa machine, en local.

corriger en mettant : Maintenant, qu'Emma a créé le projet sur Github, elle doit maintenant créer le dossier qui accueillera le projet sur sa machine, en local.

**Comment by armellarcier** [comment]
doublon https://github.com/ub-mmi-but/git-101/issues/104
