### ISSUE TITLE
Section sur la branching strategy

### ISSUE THREAD

**Issue by LeGrano** [ub-mmi-but/git-101#12]
Créer une section sur les différentes stratégies d'architectures des branches d'un projet Git.

**Comment by JosephJoeJakson** [comment]
Liens :
https://blog.mergify.com/the-best-git-branching-strategies/
https://www.engati.com/blog/git-branching-strategies
https://medium.com/cloudnloud/git-branching-strategies-a6eafe4541ae
https://www.linkedin.com/pulse/what-devops-branching-strategies-wael-al-wirr/
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/git-branching-strategies/
https://www.bmc.com/blogs/devops-branching-strategies/
https://www.gitkraken.com/learn/git/best-practices/git-branch-strategy
https://www.atlassian.com/agile/software-development/branching
https://www.abtasty.com/blog/git-branching-strategies/

**Comment by JosephJoeJakson** [comment]
Documentation sur le gitlab flow : https://about.gitlab.com/topics/version-control/what-is-gitlab-flow/
