### ISSUE TITLE
Créer une organisation github 

### ISSUE THREAD

**Issue by dCben335** [ub-mmi-but/git-101#15]
J'aimerai réaliser une série de projets avec des amis et les réunir dans une team sur Github dans laquelle tout les projets seront accessible.

Pouvez-vous donc m'indiqué si cela est possible, et si oui, comment faire ?

**Comment by Xeone971** [comment]
Absolument, vous pouvez créer une organisation sur GitHub pour regrouper plusieurs projets au sein d'une équipe. Voici comment vous pouvez procéder :

Créer un compte GitHub :
Si vous n'avez pas déjà un compte GitHub, vous devrez en créer un sur https://github.com/.

Créer une organisation :

Connectez-vous à votre compte GitHub.
Cliquez sur votre photo de profil dans le coin supérieur droit.
Sélectionnez "Your repositories" dans le menu déroulant.
Cliquez sur le bouton "New" à côté de la liste des organisations.
Remplir les informations de l'organisation :

Choisissez un nom pour votre organisation.
Ajoutez une description (optionnel).
Choisissez si vous voulez rendre l'organisation publique ou privée.
Enfin, cliquez sur le bouton "Create organization".
Inviter des membres :

Une fois l'organisation créée, allez sur la page de votre organisation.
Cliquez sur l'onglet "Members" et invitez vos amis en saisissant leurs noms d'utilisateur GitHub ou leurs adresses e-mail.
Créer des dépôts (repositories) :

Sur la page de votre organisation, cliquez sur l'onglet "Repositories".
Cliquez sur le bouton "New" pour créer un nouveau dépôt.
Répétez cette étape pour chaque projet que vous souhaitez ajouter à l'organisation.
Gérer les accès :

Vous pouvez définir les autorisations de chaque membre pour chaque dépôt en utilisant les paramètres de chaque dépôt. Par exemple, vous pouvez accorder à certains membres des droits d'écriture tandis que d'autres auront seulement des droits de lecture.
Collaborer :

Une fois les dépôts créés, les membres de votre organisation pourront cloner ces dépôts sur leurs propres machines, y contribuer et proposer des modifications via des pull requests.
Assurez-vous de bien comprendre le modèle de permissions de GitHub pour configurer les accès de manière appropriée. Cela vous permettra de collaborer efficacement sur vos projets.

**Comment by Xeone971** [comment]
Absolument, vous pouvez créer une organisation sur GitHub pour regrouper plusieurs projets au sein d'une équipe. Voici comment vous pouvez procéder :

Créer un compte GitHub :
Si vous n'avez pas déjà un compte GitHub, vous devrez en créer un sur https://github.com/.

Créer une organisation :

Connectez-vous à votre compte GitHub.
Cliquez sur votre photo de profil dans le coin supérieur droit.
Sélectionnez "Your repositories" dans le menu déroulant.
Cliquez sur le bouton "New" à côté de la liste des organisations.
Remplir les informations de l'organisation :

Choisissez un nom pour votre organisation.
Ajoutez une description (optionnel).
Choisissez si vous voulez rendre l'organisation publique ou privée.
Enfin, cliquez sur le bouton "Create organization".
Inviter des membres :

Une fois l'organisation créée, allez sur la page de votre organisation.
Cliquez sur l'onglet "Members" et invitez vos amis en saisissant leurs noms d'utilisateur GitHub ou leurs adresses e-mail.
Créer des dépôts (repositories) :

Sur la page de votre organisation, cliquez sur l'onglet "Repositories".
Cliquez sur le bouton "New" pour créer un nouveau dépôt.
Répétez cette étape pour chaque projet que vous souhaitez ajouter à l'organisation.
Gérer les accès :

Vous pouvez définir les autorisations de chaque membre pour chaque dépôt en utilisant les paramètres de chaque dépôt. Par exemple, vous pouvez accorder à certains membres des droits d'écriture tandis que d'autres auront seulement des droits de lecture.
Collaborer :

Une fois les dépôts créés, les membres de votre organisation pourront cloner ces dépôts sur leurs propres machines, y contribuer et proposer des modifications via des pull requests.
Assurez-vous de bien comprendre le modèle de permissions de GitHub pour configurer les accès de manière appropriée. Cela vous permettra de collaborer efficacement sur vos projets.
