### ISSUE TITLE
Comment gérer l'accès et les permissions des développeurs sur github

### ISSUE THREAD

**Issue by armellarcier** [ub-mmi-but/git-101#28]
Par exemple pour réserver les actions de merge sur main aux mainteneurs.

Décrire les différents rôles possibles pour les membres d'un repository github

**Comment by Xeone971** [comment]
Sur GitHub, les rôles et les autorisations des membres d'un référentiel (repository) peuvent être configurés pour définir qui peut effectuer certaines actions spécifiques. Voici les principaux rôles que vous pouvez attribuer aux membres d'un référentiel GitHub :

1. **Owner (propriétaire) :**
   - Les propriétaires ont un accès complet au référentiel.
   - Ils peuvent gérer les accès, modifier les paramètres du référentiel et effectuer des actions administratives comme la suppression du référentiel.
   - Les propriétaires ont également tous les droits d'accès aux fichiers, aux branches et aux fonctionnalités du référentiel.

2. **Collaborator (collaborateur) :**
   - Les collaborateurs ont un accès complet aux fichiers, aux branches et aux fonctionnalités du référentiel.
   - Ils peuvent ouvrir des issues, créer des pull requests, et contribuer au code.
   - Cependant, ils n'ont pas les droits administratifs du propriétaire.

3. **Maintainer (mainteneur) :**
   - Les mainteneurs peuvent être considérés comme des collaborateurs avec des droits supplémentaires pour gérer les fonctionnalités de fusion (merge) et de gestion des branches.
   - Ils peuvent généralement approuver et fusionner des pull requests.
   - Certains projets utilisent le terme "maintainer" pour décrire ceux qui ont le droit de fusionner des changements dans certaines branches (comme la branche principale, souvent nommée "main").

4. **Contributor (contributeur) :**
   - Les contributeurs sont généralement ceux qui n'ont pas un accès direct au référentiel mais qui peuvent contribuer en proposant des changements via des pull requests.
   - Ils peuvent créer des branches, ouvrir des pull requests et participer à la discussion.

5. **Read-only (lecture seule) :**
   - Certains référentiels peuvent attribuer des droits en lecture seule à certains membres.
   - Les utilisateurs en lecture seule peuvent consulter le code source et les problèmes, mais ils ne peuvent pas apporter de modifications directes.

Ces rôles peuvent être ajustés et personnalisés en fonction des besoins spécifiques du projet. La gestion des rôles se fait à partir des paramètres du référentiel, dans la section "Settings" > "Manage access" sur GitHub. Les propriétaires du référentiel peuvent définir les rôles des membres en fonction de leurs responsabilités et de leurs niveaux d'accès nécessaires.
