### ISSUE TITLE
Erreurs/problèmes récurrents avec Git

### ISSUE THREAD

**Issue by LeGrano** [ub-mmi-but/git-101#66]
- Branche qui change de nom et crée un conflit : 
- Problème pas possible de push car push par dessus notre travail en cours 
- Récupérer des fichiers accidentellement supprimés 
- Supprimer une branche trop tôt
- Commit du code non terminés
- Conflits de merge
- Erreur Permission Denied (Publickey)
- Un fichier de dépendances à été ajouté (git ignore)
- Premier git push qui génère une erreur
- fatal: not a git repository
-PIRE cas avec git : Se rebase sur une branche qui n'est pas main et qui est elle même une copie. Cela provoque une tonne de conflits car "l'ancêtre" commun est lointain. Pour éviter il faut préciser de quel commit on part. (commande --onto)

**Comment by armellarcier** [comment]
C fait
